import {json,href,escape as e,date,recordTitle,matches,sourceLink} from './shared.js';
const page = document.body.dataset.page;
const $ = selector => document.querySelector(selector);
const params = new URLSearchParams(location.search);
function unavailable(target, label='This information') { $(target).innerHTML=`<div class="empty-state"><h2>${label} is temporarily unavailable</h2><p>The last saved record could not be loaded. Please use the <a href="https://www.miamibeachfl.gov/" target="_blank" rel="noreferrer">official City website</a>.</p><button class="hub-button secondary" onclick="location.reload()">Try again</button></div>`; }
function updateQuery(values) { const q=new URLSearchParams(); Object.entries(values).forEach(([key,value])=>{if(value && value!=='all')q.set(key,value);});history.replaceState(null,'',location.pathname+(q.size?'?'+q:'')); }
function guidePage() {
 const query=$('#guide-search'), category=$('#guide-category'); query.value=params.get('q')||'';
 const run=()=>{let count=0; document.querySelectorAll('.topic-card').forEach(card=>{const show=matches(query.value,card.dataset.search)&&(category.value==='all'||card.dataset.category===category.value);card.hidden=!show;if(show)count++;});$('#guide-count').textContent=`${count} resident ${count===1?'resource':'resources'}`;$('#guide-empty').hidden=count>0;};
 query.addEventListener('input',run); category.addEventListener('change',run);run();
}
async function meetingsPage() {
 const results=await Promise.allSettled([json('city-agenda'),json('city-calendar'),json('commission-actions')]);
 const [agenda,calendar,actions]=results.map(r=>r.status==='fulfilled'?r.value:null);
 if(agenda){const m=agenda.nextMeeting;$('#next-meeting').innerHTML=`<div class="help-box next-meeting"><div><span class="source-note">NEXT AVAILABLE COMMISSION AGENDA</span><h2>${date(m.date)}</h2><p>${e(m.location)} · ${m.itemCount} listed items</p></div><div class="button-row"><a class="hub-button" href="../commission-agenda/">Read the agenda</a><a class="hub-button secondary" href="${e(m.officialAgendaUrl)}" target="_blank" rel="noreferrer">Official meeting packet ↗</a></div></div>`;}else unavailable('#next-meeting','The next agenda');
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York'}).format(new Date());
 if(calendar){const items=calendar.items.filter(i=>(i.endLocal||i.startLocal).slice(0,10)>=today);$('#upcoming-meetings').innerHTML=items.length?items.map((i,index)=>{const d=new Date(i.startLocal.slice(0,10)+'T12:00:00');const time=i.startLocal.includes('T')?i.startLocal.slice(11,16):'All day';return `<article class="event-row"${index>=12?' hidden':'' }><time class="date-block" datetime="${e(i.startLocal)}">${d.toLocaleDateString('en-US',{month:'short'})}<b>${d.getDate()}</b></time><div><h3>${e(i.title.replace(/\*$/,''))}</h3><p>${time==='All day'?time:new Date('2000-01-01T'+time).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'})+' ET'} · ${e(i.location||'See meeting notice')}</p>${i.note?`<p class="notice">${e(i.note)}</p>`:''}${sourceLink(i.url,'Meeting details & access')}</div></article>`;}).join(''):'<p>No upcoming events appear in the current calendar snapshot. Check the full City calendar.</p>';$('#upcoming-meetings').insertAdjacentHTML('beforeend',`<p class="source-note">Calendar snapshot saved ${date(calendar.generatedAt)}. ${items.length} upcoming events in the saved feed. Dates and access details can change.</p>`);if(items.length>12){const button=document.createElement('button');button.className='hub-button secondary';button.textContent='Show all '+items.length+' upcoming events';button.addEventListener('click',()=>{$('#upcoming-meetings').querySelectorAll('[hidden]').forEach(el=>el.hidden=false);button.remove();});$('#upcoming-meetings').append(button);}
const conflict=items.find(i=>i.note&&i.startLocal.slice(0,10)===agenda?.nextMeeting.date);if(conflict)$('#next-meeting').insertAdjacentHTML('beforeend','<p class="notice">'+e(conflict.note)+' <a href="https://www.miamibeachfl.gov/city-hall/city-clerk/city-commission-meeting-dates/" target="_blank" rel="noreferrer">Official commission schedule ↗</a></p>');
}else unavailable('#upcoming-meetings','The meeting calendar');
 if(actions)$('#meeting-history').innerHTML=`<div class="table-wrap"><table class="hub-table"><thead><tr><th scope="col">Meeting</th><th scope="col">Record</th><th scope="col">Explore</th></tr></thead><tbody>${[...actions.meetings].reverse().map(m=>`<tr><td><strong>${date(m.date,true)}</strong><br>${e(m.title)}</td><td>${e(m.minutesStatus)}${m.minutesUrl?'<br>'+sourceLink(m.minutesUrl,'Approved minutes'):''}</td><td>${m.itemCount?`<a href="../commission-actions/?meeting=${m.date}&outcome=all">${m.itemCount} recorded actions</a>`:'Awaiting record'}${m.videoUrl?'<br>'+sourceLink(m.videoUrl,'Watch recording'):''}</td></tr>`).join('')}</tbody></table></div>`;else unavailable('#meeting-history','Meeting history');
}
async function newsPage(){const data=await json('city-news');const run=()=>{const items=data.items.filter(i=>matches($('#news-search').value,i.title));$('#news-status').textContent=`${items.length} official announcements · Snapshot saved ${date(data.generatedAt)}`;$('#news-list').innerHTML=items.length?items.map(i=>`<article class="result-row"><time class="row-kind" datetime="${e(i.publishedAt)}">${date(i.publishedAt,true)}</time><div><h2>${sourceLink(i.url,i.title)}</h2><p>City of Miami Beach · Official announcement</p></div></article>`).join(''):'<div class="empty-state">No announcements match this search.</div>';};$('#news-search').addEventListener('input',run);run();}
async function aboutPage(){const data=await json('commissioners');$('#official-people').innerHTML=data.items.map(p=>`<article class="person"><a href="${e(p.profileUrl)}" target="_blank" rel="noreferrer"><img src="${e(p.portrait)}" alt="Official City portrait of ${e(p.name)}" loading="lazy"><h3>${e(p.name)}</h3></a><p>${e(p.title)}${p.group?' · '+e(p.group):''}</p></article>`).join('');}
async function sourcesPage(){
 const health=await json('sync-status').catch(()=>null);
 const specs=[['city-agenda','Next commission agenda',d=>`${d.items.length} items for ${date(d.nextMeeting.date)}`,'commission-agenda/'],['commission-actions','Decisions & votes',d=>`${d.items.length.toLocaleString()} extracted actions · ${d.coverage.publishedMinutesCount} published meeting records · Through ${date(d.coverage.throughDate)}`,'commission-actions/'],['city-projects','Public Works projects',d=>`${d.items.length} GIS features; several features can describe one project.`,'active-projects/'],['youtube','David’s video archive',d=>`${d.items.length} indexed videos. Recent uploads are merged into this archive; it is not a complete channel export.`,'media/'],['city-calendar','Public meeting calendar',d=>`${d.items.length} upcoming events in the saved feed.`,'meetings/'],['city-news','City announcements',d=>`${d.items.length} recent press releases.`,'news/'],['records-status','Ordinance & resolution registries',d=>d.items.map(i=>`${i.type}: through ${date(i.currentThrough,true)}`).join(' · '),'legislation/']];
 const results=await Promise.allSettled(specs.map(([file])=>json(file)));
 $('#source-status').innerHTML=results.map((r,index)=>{const [file,title,coverage,route]=specs[index];if(r.status!=='fulfilled')return `<article class="result-row"><span class="row-kind">Unavailable</span><div><h3>${title}</h3><p>The snapshot could not be loaded.</p></div></article>`;const d=r.value;const job={'city-agenda':'agendas','commission-actions':'actions','city-projects':'projects','youtube':'youtube','city-calendar':'calendar','city-news':'news','records-status':'records'}[file];const healthItem=health?.items?.find(i=>i.name===job);const checkedAt=healthItem?.status==='success'?healthItem.checkedAt:d.generatedAt;const stale=Date.now()-new Date(checkedAt)>48*3600000;return `<article class="result-row"><span class="row-kind">${stale?'Check freshness':'Saved snapshot'}</span><div><h3><a href="../${route}">${title}</a></h3><p>${e(coverage(d))}</p><p>Snapshot saved ${date(d.generatedAt)} · Last successful check ${date(checkedAt)} at ${new Date(checkedAt).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit',timeZone:'America/New_York'})} ET${stale?' · More than 48 hours ago':''}</p>${sourceLink(file==='commission-actions'?'https://miamibeachfl.primegov.com/public/portal?fromiframe=true':d.source.url,d.source.label)}</div></article>`;}).join('');
 if(health?.items?.some(i=>i.status==='failed'))$('#source-status').insertAdjacentHTML('afterbegin','<div class="notice"><strong>Some sources could not be refreshed.</strong><p>'+health.items.filter(i=>i.status==='failed').map(i=>e(i.name)).join(', ')+'. The last validated snapshots remain available. Check the original sources for newer information.</p></div>');
}
async function lawPage(){
 const [agenda,actions,registries]=await Promise.all([json('city-agenda'),json('commission-actions'),json('records-status')]); let limit=30;
 $('#law-search').value=params.get('q')||'';if(params.get('stage')==='recorded')$('#law-stage').value='recorded';
 const run=()=>{const upcoming=$('#law-stage').value==='upcoming';const items=(upcoming?agenda.items:actions.items).map(i=>({...i,lawType:upcoming?i.type:/^R5\s/i.test(i.itemNumber)?'Ordinance':/^(C7|R7)\s/i.test(i.itemNumber)?'Resolution':''})).filter(i=>['Ordinance','Resolution'].includes(i.lawType)&&($('#law-type').value==='all'||$('#law-type').value===i.lawType)&&matches($('#law-search').value,[i.itemNumber,i.title,i.officialTitle,i.action].join(' '))).sort((a,b)=>upcoming?0:b.meetingDate.localeCompare(a.meetingDate));
 $('#law-count').textContent=`${items.length} ${upcoming?'upcoming items':'recorded actions'} · ${upcoming?date(agenda.nextMeeting.date):'2026 approved minutes'}`;
 $('#law-list').innerHTML=items.length?items.slice(0,limit).map(i=>`<article class="result-row"><span class="row-kind">${e(i.itemNumber)}<br>${i.lawType}</span><div><h2><a href="../${upcoming?'commission-agenda':'commission-actions'}/?item=${encodeURIComponent(i.id)}">${e(upcoming?i.title:recordTitle(i.title))}</a></h2><p>${upcoming?'Scheduled for consideration':e(i.outcome)} · ${date(i.meetingDate,true)}${!upcoming&&i.voteSummary?' · Recorded vote '+e(i.voteSummary):''}</p>${!upcoming?`<p>${e(i.action.slice(0,220))}${i.action.length>220?'…':''}</p>`:''}<a class="source-note" href="../${upcoming?'commission-agenda':'commission-actions'}/?item=${encodeURIComponent(i.id)}">Read the item & source</a></div></article>`).join(''):'<div class="empty-state">No legislation matches. Try another keyword or record stage.</div>';$('#law-more').hidden=items.length<=limit;};
 ['#law-search','#law-stage','#law-type'].forEach(id=>$(id).addEventListener(id==='#law-search'?'input':'change',()=>{limit=30;run();}));$('#law-more').addEventListener('click',()=>{limit+=30;run();});
 $('#law-registries').innerHTML=registries.items.map(r=>`<article class="help-box"><h2>${r.type==='ordinances'?'Ordinance':'Resolution'} registry</h2><p>Published index through ${date(r.currentThrough)}. This coverage date may lag the latest approved minutes.</p><div class="button-row"><a class="hub-button secondary" href="${e(r.registryPdf)}" target="_blank" rel="noreferrer">Open official index PDF ↗</a><a href="${e(r.recordsDirectory)}" target="_blank" rel="noreferrer">Document archive ↗</a></div></article>`).join('');run();
}
async function searchPage(){
 const files=['city-agenda','commission-actions','city-projects','youtube','resident-guide','city-news'];const results=await Promise.allSettled(files.map(json));let records=[],category=params.get('type')||'All',limit=30;
 results.forEach((r,index)=>{if(r.status!=='fulfilled')return;const d=r.value;const type=['Agenda','Decisions','Projects','Videos','Services','News'][index];records.push(...d.items.map(i=>({type,title:i.title,text:[i.title,i.officialTitle,i.itemNumber,i.action,i.description,i.neighborhood,i.series,i.keywords,...(i.sponsors||[])].join(' '),description:index===0?`${i.itemNumber} · ${i.section} · ${date(i.meetingDate,true)}`:index===1?`${i.itemNumber} · ${i.outcome} · ${date(i.meetingDate,true)}`:index===2?`${i.phase} · ${i.neighborhood||'Citywide'}`:index===3?`${i.series} · David’s commentary` : index===4?i.description:`Official City announcement · ${date(i.publishedAt,true)}`,url:index===0?href(`commission-agenda/?item=${encodeURIComponent(i.id)}`):index===1?href(`commission-actions/?item=${encodeURIComponent(i.id)}`):index===2?href(`active-projects/?project=${encodeURIComponent(i.id)}`):index===3?href(`media/?video=${i.id}`):index===4?href(`resident-guide/#${i.id}`):i.url})));});
 $('#global-query').value=params.get('q')||'';
 const run=()=>{const query=$('#global-query').value.trim();const matched=query?records.filter(i=>matches(query,i.text)).sort((a,b)=>(Number(matches(query,b.title))*20+Number(b.type==='Services')*50)-(Number(matches(query,a.title))*20+Number(a.type==='Services')*50)):[];const types=['All','Services','Agenda','Decisions','Projects','Videos','News'];if(!types.includes(category))category='All';
 $('#search-tabs').innerHTML=types.map(t=>`<button type="button" data-type="${t}" aria-pressed="${category===t}">${t}${query?' '+(t==='All'?matched.length:matched.filter(i=>i.type===t).length):''}</button>`).join('');
 const shown=matched.filter(i=>category==='All'||i.type===category);const failed=results.filter(r=>r.status==='rejected').length;$('#search-status').textContent=query?`${shown.length.toLocaleString()} results for “${query}”${failed?' · Some sources could not be loaded':''}`:`Search across ${records.length.toLocaleString()} indexed records and resources${failed?' · Some sources unavailable':''}.`;
 $('#search-results').innerHTML=!query?`<div class="help-box"><h2>Start with what matters to you.</h2><div class="button-row">${['North Beach','parking','budget','flooding','Suarez Sound Off'].map(q=>`<a class="hub-button secondary" href="?q=${encodeURIComponent(q)}">${q}</a>`).join('')}</div></div>`:shown.length?shown.slice(0,limit).map(i=>`<article class="result-row"><span class="row-kind">${i.type}</span><div><h2><a href="${e(i.url)}">${e(recordTitle(i.title,180))}</a></h2><p>${e(i.description)}</p></div></article>`).join(''):'<div class="empty-state"><h2>No matching results</h2><p>Try fewer words, a different spelling or another result type.</p><a href="../resident-guide/">Browse resident services</a></div>';
 $('#more-results').hidden=shown.length<=limit;updateQuery({q:query,type:category==='All'?'':category});};
 $('#global-search-form').addEventListener('submit',event=>{event.preventDefault();limit=30;run();});$('#search-tabs').addEventListener('click',event=>{const b=event.target.closest('[data-type]');if(b){category=b.dataset.type;limit=30;run();}});$('#more-results').addEventListener('click',()=>{limit+=30;run();});run();
}
const handlers={'resident-guide':[guidePage,'#guide-list'],'meetings':[meetingsPage,'#upcoming-meetings'],'news':[newsPage,'#news-list'],'about':[aboutPage,'#official-people'],'sources':[sourcesPage,'#source-status'],'legislation':[lawPage,'#law-list'],'search':[searchPage,'#search-results']};
if(handlers[page]){const [run,target]=handlers[page];Promise.resolve().then(run).catch(error=>{console.error(error);unavailable(target);});}
