import {json,escape as e,matches,date,sourceLink} from '../shared.js';
const $=s=>document.querySelector(s),params=new URLSearchParams(location.search);
const state={dataset:'works',datasets:{},selected:params.get('project'),center:null,map:null,markers:null};
const clean=v=>v && String(v).toLowerCase()!=='null'?String(v):'';
const distance=(a,b)=>{const r=x=>x*Math.PI/180,dlat=r(b.lat-a.lat),dlng=r(b.lng-a.lng);return 3958.8*2*Math.atan2(Math.sqrt(Math.sin(dlat/2)**2+Math.cos(r(a.lat))*Math.cos(r(b.lat))*Math.sin(dlng/2)**2),Math.sqrt(1-(Math.sin(dlat/2)**2+Math.cos(r(a.lat))*Math.cos(r(b.lat))*Math.sin(dlng/2)**2)));};
function items(){return (state.datasets[state.dataset]?.items||[]).filter(i=>matches($('#project-search').value,[i.title,i.description,i.neighborhood,i.corridor,i.limits].join(' '))&&($('#project-neighborhood').value==='all'||i.neighborhood===$('#project-neighborhood').value)&&($('#project-phase').value==='all'||i.phase===$('#project-phase').value)&&(!state.center||Number.isFinite(i.lat)&&Number.isFinite(i.lng)&&distance(state.center,i)<=Number($('#project-radius').value))).sort((a,b)=>state.center?distance(state.center,a)-distance(state.center,b):a.title.localeCompare(b.title));}
function filters(){const data=state.datasets[state.dataset]?.items||[];[['#project-neighborhood','neighborhood','All neighborhoods'],['#project-phase','phase','All phases']].forEach(([selector,key,label])=>{$(selector).innerHTML=`<option value="all">${label}</option>`+[...new Set(data.map(i=>i[key]).filter(Boolean))].sort().map(v=>`<option>${e(v)}</option>`).join('');});$('#project-source').textContent=state.datasets[state.dataset]?.note||'This dataset could not be loaded.';}
function select(id,move=false){const item=state.datasets[state.dataset]?.items.find(i=>i.id===id);if(!item)return;state.selected=id;document.querySelectorAll('[data-project]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.project===id)));$('#project-detail').innerHTML=`<h2>${e(item.title)}</h2><p>${e(item.description||'No project description is available in this source. Open the official record for details.')}</p><dl><div><dt>Neighborhood</dt><dd>${e(item.neighborhood||'Not specified')}</dd></div><div><dt>Phase / status</dt><dd>${e([item.phase,item.status].filter(Boolean).join(' · ')||'Not specified')}</dd></div>${item.limits?`<div><dt>Project limits</dt><dd>${e(item.limits)}</dd></div>`:''}${item.totalNeed?`<div><dt>Estimated need in source</dt><dd>${new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(item.totalNeed)}<br>Not a confirmed appropriation</dd></div>`:''}</dl><div class="button-row">${sourceLink(item.link||state.datasets[state.dataset].source,'Open project source')}<button class="hub-button secondary" data-copy-link>Copy link</button></div>`;const p=new URLSearchParams({project:id});if(state.dataset!=='works')p.set('dataset',state.dataset);history.replaceState(null,'',location.pathname+'?'+p);if(move&&state.map&&Number.isFinite(item.lat)&&Number.isFinite(item.lng))state.map.setView([item.lat,item.lng],15);if(move&&matchMedia('(max-width:860px)').matches){$('#project-detail').scrollIntoView({behavior:'smooth'});$('#project-detail').focus({preventScroll:true});}}
function render(){const list=items();$('#project-count').textContent=`${list.length} ${state.dataset==='works'?'project map features':'projects'}${state.center?' near '+state.center.label:''}`;$('#project-results').innerHTML=list.length?list.map(i=>`<button class="project-result" type="button" data-project="${e(i.id)}" aria-pressed="${state.selected===i.id}"><span>${e(i.phase||'Project')} · ${e(i.neighborhood||'Citywide')}</span><h2>${e(i.title)}</h2><p>${e(i.status||i.limits||'Open for project details')}${state.center?' · '+distance(state.center,i).toFixed(1)+' mi':''}</p></button>`).join(''):'<div class="empty-state"><h2>No matching projects</h2><p>Try a wider area or clear your filters.</p></div>';if(state.markers){state.markers.clearLayers();list.filter(i=>Number.isFinite(i.lat)&&Number.isFinite(i.lng)).forEach(i=>{const marker=L.circleMarker([i.lat,i.lng],{radius:7,color:'#fff',weight:2,fillColor:i.phase==='Construction'?'#d84528':'#086c67',fillOpacity:1}).addTo(state.markers);marker.bindTooltip(e(i.title));marker.on('click',()=>select(i.id));});if(list.length&&!state.center){const pts=list.filter(i=>Number.isFinite(i.lat)&&Number.isFinite(i.lng)).map(i=>[i.lat,i.lng]);if(pts.length)state.map.fitBounds(pts,{padding:[25,25],maxZoom:14});}}
 if(!list.some(i=>i.id===state.selected))state.selected=list[0]?.id;if(state.selected)select(state.selected);else $('#project-detail').innerHTML='<p>Select a project to read its details and source.</p>';
}
async function initialize(){const results=await Promise.allSettled([json('city-projects'),fetch('data/projects.json').then(r=>{if(!r.ok)throw Error('directory unavailable');return r.json();}),fetch('data/future-projects.json').then(r=>{if(!r.ok)throw Error('future unavailable');return r.json();})]);
 if(results[0].status==='fulfilled'){const d=results[0].value;state.datasets.works={items:d.items.map(i=>({...i,neighborhood:clean(i.neighborhood),phase:clean(i.phase),status:clean(i.status),description:clean(i.description),limits:clean(i.limits),corridor:clean(i.corridor)})),source:d.source.url,note:`City Public Works GIS · Snapshot saved ${date(d.generatedAt)}. Counts represent mapped features; one project may appear more than once.`};}
 if(results[1].status==='fulfilled')state.datasets.neighborhood={items:results[1].value.map(i=>({...i,description:i.summary,neighborhood:i.hood,phase:i.category})),source:'https://www.miamibeachfl.gov/city-hall/cip/active-projects/',note:'Selected City neighborhood-project directory entries from the saved project catalog. This editorial catalog is separate from the automatically refreshed Public Works GIS. Confirm current status on each linked City page.'};
 if(results[2].status==='fulfilled')state.datasets.future={items:results[2].value.map(i=>({...i,description:i.summary,neighborhood:i.hood,phase:i.phaseWindow,status:'Future need — not confirmed funding',link:'https://docs.google.com/presentation/d/1I7hCgh6ZmT26NXUE4aO2mQmtftqUYn6f/edit'})),source:'https://docs.google.com/presentation/d/1I7hCgh6ZmT26NXUE4aO2mQmtftqUYn6f/edit',note:'Future needs from the June 5, 2026 Critical Infrastructure Funding presentation. Planning estimates and approximate map points—not active construction or confirmed appropriations.'};
 state.dataset=Object.keys(state.datasets).includes(params.get('dataset'))?params.get('dataset'):'works';$('#project-search').value=params.get('q')||'';
 if(typeof L!=='undefined'){state.map=L.map('project-map',{scrollWheelZoom:false}).setView([25.815,-80.13],12);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(state.map);state.markers=L.layerGroup().addTo(state.map);}else $('#project-map').innerHTML='<p class="notice">The interactive map could not load. All project details are available in the list.</p>';
 filters();render();document.querySelectorAll('[data-dataset]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.dataset===state.dataset)));
}
$('#project-results').addEventListener('click',event=>{const b=event.target.closest('[data-project]');if(b)select(b.dataset.project,true);});
$('#dataset-tabs').addEventListener('click',event=>{const b=event.target.closest('[data-dataset]');if(!b)return;state.dataset=b.dataset.dataset;document.querySelectorAll('[data-dataset]').forEach(el=>el.setAttribute('aria-pressed',String(el===b)));filters();render();});
['#project-search','#project-neighborhood','#project-phase','#project-radius'].forEach(selector=>$(selector).addEventListener(selector==='#project-search'?'input':'change',render));
$('#address-form').addEventListener('submit',async event=>{event.preventDefault();$('#address-results').textContent='Finding matching addresses…';try{const q=$('#address-input').value.trim();const p=new URLSearchParams({f:'json',SingleLine:q+', Miami Beach, FL',outFields:'Match_addr',maxLocations:'4',searchExtent:'-80.20,25.75,-80.10,25.88'});const r=await fetch('https://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/findAddressCandidates?'+p);if(!r.ok)throw Error('geocoding unavailable');const d=await r.json();const candidates=(d.candidates||[]).filter(c=>c.location.x>=-80.2&&c.location.x<=-80.1&&c.location.y>=25.75&&c.location.y<=25.88);$('#address-results').innerHTML=candidates.length?'<p>Select your address:</p>':'No matching Miami Beach address was found. Try a street address or search by neighborhood.';candidates.forEach(c=>{const b=document.createElement('button');b.type='button';b.textContent=c.address;b.addEventListener('click',()=>{state.center={lat:c.location.y,lng:c.location.x,label:c.address};$('#address-results').textContent='Using '+c.address;$('#clear-address').hidden=false;state.map?.setView([c.location.y,c.location.x],14);render();});$('#address-results').append(b);});}catch{$('#address-results').textContent='Address lookup is unavailable. You can still search projects by street or neighborhood.';}});
$('#clear-address').addEventListener('click',()=>{state.center=null;$('#address-results').textContent='';$('#clear-address').hidden=true;render();});
initialize().catch(error=>{console.error(error);$('#project-count').textContent='Projects could not be loaded. Please use the official City project directory.';});
