export function homeLayout(){return `<main id="main">
  <section class="coastal-hero" aria-labelledby="home-title">
    <img class="coastal-poster" src="assets/miami-beach-opening.jpg" alt="Miami Beach coastline and ocean" width="1600" height="900" fetchpriority="high">
    <video id="hero-film" class="coastal-film" muted loop playsinline preload="none" data-video-src="assets/miami-beach-opening.mp4" data-mobile-src="assets/miami-beach-opening-mobile.mp4" aria-hidden="true" tabindex="-1"></video>
    <div class="container hero-content"><p class="hero-identity">David Suarez · Miami Beach Commissioner</p><h1 id="home-title">Your Miami Beach.</h1><div class="hero-links"><a class="visual-button" href="#explore">Explore your city <span aria-hidden="true">↘</span></a><a class="visual-button secondary" href="#top">Watch David</a></div></div>
  </section>
  <section class="city-discovery container" id="explore" aria-labelledby="explore-title"><div class="discovery-heading"><h2 id="explore-title">Projects in your neighborhood</h2></div><div class="discovery-layout"><div class="home-map-sidebar"><label class="hub-field">Choose your neighborhood<select id="home-neighborhood"><option value="all">All Miami Beach</option></select></label><p id="home-map-count" class="source-note" aria-live="polite"></p><div id="home-project-list" aria-live="polite"><p class="source-note">Loading city projects…</p></div><a class="visual-button secondary" id="home-map-link" href="active-projects/">Explore all projects <span aria-hidden="true">↗</span></a></div><div class="home-map-frame"><div id="home-project-map" role="region" aria-label="Interactive map of Miami Beach projects" aria-busy="true"><div class="map-loading"><p>Loading the project map…</p><a href="active-projects/">Open the project directory</a></div></div><div id="home-map-legend"></div><p class="home-map-note">City neighborhood boundaries · Project points are approximate. <a href="sources/">Data & sources</a></p></div></div></section>
  <section class="city-today container" aria-labelledby="today-title"><div class="section-line"><div><h2 id="today-title">Miami Beach Today</h2></div><a class="today-all" href="news/">All announcements ↗</a></div><div class="official-updates" id="official-updates" aria-live="polite"></div></section>
  <section class="home-watch" id="top" aria-labelledby="watch-title"><div class="container"><div class="section-line"><h2 id="watch-title">Watch David</h2><a href="media/">All videos ↗</a></div><article class="featured-story" id="featured-story" aria-labelledby="featured-title"><img id="featured-image" src="https://i.ytimg.com/vi/BBupCl9Bc2w/maxresdefault.jpg" alt="Suarez Sound Off with Jeffrey Soffer" width="1280" height="720" loading="lazy"><div class="featured-content"><div class="featured-copy"><h2 id="featured-title">The visionary behind Fontainebleau</h2><div class="featured-meta"><span id="featured-series">Suarez Sound Off</span><span id="featured-date">August 31, 2026</span></div></div><div class="featured-actions"><a class="button" id="featured-link" href="media/?video=BBupCl9Bc2w">Watch episode <span aria-hidden="true">↗</span></a></div></div></article>
  <div class="series-grid" id="media"><a class="series-card" href="media/?series=Suarez%20Sound%20Off"><img src="https://i.ytimg.com/vi/js-31vl7Q6g/maxresdefault.jpg" alt="Suarez Sound Off with Kobi Karp" width="1280" height="720" loading="lazy"><span class="series-copy"><strong>Suarez Sound Off</strong></span></a><a class="series-card" href="media/?series=Miami%20Beach%20Civics"><img src="https://i.ytimg.com/vi/aOT06J6D6OM/maxresdefault.jpg" alt="Miami Beach Civics: Where does your money go?" width="1280" height="720" loading="lazy"><span class="series-copy"><strong>Miami Beach Civics</strong></span></a><a class="series-card" href="media/?series=Ride%20Along"><img src="https://i.ytimg.com/vi/2fU3AA-g20k/maxresdefault.jpg" alt="David with a Miami Beach sanitation crew" width="1280" height="720" loading="lazy"><span class="series-copy"><strong>Ride Along</strong></span></a><a class="series-card" href="media/?series=Accountability"><img src="https://i.ytimg.com/vi/V2sDUO2tT5Y/maxresdefault.jpg" alt="David’s public accountability reporting" width="1280" height="720" loading="lazy"><span class="series-copy"><strong>Accountability</strong></span></a></div></div></section>
  <nav class="container city-hall-links" aria-label="Explore City Hall"><a href="commission-agenda/">Next agenda ↗</a><a href="commission-actions/">Decisions & votes ↗</a><a href="meetings/">Meetings & participation ↗</a><a href="resident-guide/">Resident services ↗</a></nav>
  <section class="home-contact"><div class="container"><h2>David’s office</h2><a class="hub-button" href="about/">Contact David’s office</a></div></section>
  <p class="container source-note"><a href="sources/#visual-credits">Footage & image credits</a></p>
</main>`;}
